[0m[[0m[0mdebug[0m] [0m[0mnot up to date. inChanged = true, force = false[0m
[0m[[0m[0mdebug[0m] [0m[0mUpdating ProjectRef(uri("file:/D:/MyWork/ScalaProj/DandRiscvSoC/project/"), "dandriscvsoc-build")...[0m
[0m[[0m[0mdebug[0m] [0m[0mDone updating ProjectRef(uri("file:/D:/MyWork/ScalaProj/DandRiscvS[error] lmcoursier.internal.shaded.coursier.error.FetchError$DownloadingArtifacts: Error fetching artifacts:
[error] https://repo1.maven.org/maven2/io/get-coursier/interface/0.0.17/interface-0.0.17.jar: download error: Caught java.nio.file.AccessDeniedException (C:\Users\TsinghuaIC\AppData\Local\Coursier\Cache\v1\https\repo1.maven.org\maven2\io\get-coursier\interface\0.0.17\.interface-0.0.17.jar.part -> C:\Users\TsinghuaIC\AppData\Local\Coursier\Cache\v1\https\repo1.maven.org\maven2\io\get-coursier\interface\0.0.17\interface-0.0.17.jar) while downloading https://repo1.maven.org/maven2/io/get-coursier/interface/0.0.17/interface-0.0.17.jar
[error] 
[error] 	at lmcoursier.internal.shaded.coursier.Artifacts$.$anonfun$fetchArtifacts$9(Artifacts.scala:365)
[error] 	at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$extension$1(Task.scala:14)
[error] 	at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$extension$1$adapted(Task.scala:14)
[error] 	at lmcoursier.internal.shaded.coursier.util.Task$.wrap(Task.scala:82)
[error] 	at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
[error] 	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
[error] 	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:750)
[error] Caused by: lmcoursier.internal.shaded.coursier.cache.ArtifactError$DownloadError: download error: Caught java.nio.file.AccessDeniedException (C:\Users\TsinghuaIC\AppData\Local\Coursier\Cache\v1\https\repo1.maven.org\maven2\io\get-coursier\interface\0.0.17\.interface-0.0.17.jar.part -> C:\Users\TsinghuaIC\AppData\Local\Coursier\Cache\v1\https\repo1.maven.org\maven2\io\get-coursier\interface\0.0.17\interface-0.0.17.jar) while downloading https://repo1.maven.org/maven2/io/get-coursier/interface/0.0.17/interface-0.0.17.jar
[error] 	at lmcoursier.internal.shaded.coursier.cache.internal.Downloader$.helper$2(Downloader.scala:748)
[error] 	at lmcoursier.internal.shaded.coursier.cache.internal.Downloader$.coursier$cache$internal$Downloader$$downloading(Downloader.scala:761)
[error] 	at lmcoursier.internal.shaded.coursier.cache.internal.Downloader$Blocking$.$anonfun$remote$1(Downloader.scala:406)
[error] 	at lmcoursier.internal.shaded.coursier.cache.CacheLocks$.loop$1(CacheLocks.scala:71)
[error] 	at lmcoursier.internal.shaded.coursier.cache.CacheLocks$.withLockOr(CacheLocks.scala:95)
[error] 	at lmcoursier.internal.shaded.coursier.cache.internal.Downloader$Blocking$.remote(Downloader.scala:408)
[error] 	at lmcoursier.internal.shaded.coursier.cache.internal.Downloader.$anonfun$remote$5(Downloader.scala:510)
[error] 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[error] 	at scala.util.Success.$anonfun$map$1(Try.scala:255)
[error] 	at scala.util.Success.map(Try.scala:213)
[error] 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[error] 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[error] 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:750)
[error] Caused by: java.nio.file.AccessDeniedException: C:\Users\TsinghuaIC\AppData\Local\Coursier\Cache\v1\https\repo1.maven.org\maven2\io\get-coursier\interface\0.0.17\.interface-0.0.17.jar.part -> C:\Users\TsinghuaIC\AppData\Local\Coursier\Cache\v1\https\repo1.maven.org\maven2\io\get-coursier\interface\0.0.17\interface-0.0.17.jar
[error] 	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
[error] 	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
[error] 	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301)
[error] 	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:291)
[error] 	at java.nio.file.Files.move(Files.java:1395)
[error] 	at lmcoursier.internal.shaded.coursier.cache.internal.Downloader$Blocking$.$anonfun$doDownload$14(Downloader.scala:291)
[error] 	at lmcoursier.internal.shaded.coursier.cache.CacheLocks$$anon$1.call(CacheLocks.scala:20)
[error] 	at lmcoursier.internal.shaded.coursier.paths.CachePath.withStructureLock(CachePath.java:151)
[error] 	at lmcoursier.internal.shaded.coursier.cache.CacheLocks$.withStructureLock(CacheLocks.scala:20)
[error] 	at lmcoursier.internal.shaded.coursier.cache.internal.Downloader$Blocking$.doDownload(Downloader.scala:289)
[error] 	at lmcoursier.internal.shaded.coursier.cache.internal.Downloader$Blocking$.$anonfun$remote$2(Downloader.scala:406)
[error] 	at lmcoursier.internal.shaded.coursier.cache.internal.Downloader$.$anonfun$downloading$1(Downloader.scala:715)
[error] 	at lmcoursier.internal.shaded.coursier.cache.CacheLocks$.withUrlLock(CacheLocks.scala:114)
[error] 	at lmcoursier.internal.shaded.coursier.cache.internal.Downloader$.helper$2(Downloader.scala:715)
[error] 	at lmcoursier.internal.shaded.coursier.cache.internal.Downloader$.coursier$cache$internal$Downloader$$downloading(Downloader.scala:761)
[error] 	at lmcoursier.internal.shaded.coursier.cache.internal.Downloader$Blocking$.$anonfun$remote$1(Downloader.scala:406)
[error] 	at lmcoursier.internal.shaded.coursier.cache.CacheLocks$.loop$1(CacheLocks.scala:71)
[error] 	at lmcoursier.internal.shaded.coursier.cache.CacheLocks$.withLockOr(CacheLocks.scala:95)
[error] 	at lmcoursier.internal.shaded.coursier.cache.internal.Downloader$Blocking$.remote(Downloader.scala:408)
[error] 	at lmcoursier.internal.shaded.coursier.cache.internal.Downloader.$anonfun$remote$5(Downloader.scala:510)
[error] 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[error] 	at scala.util.Success.$anonfun$map$1(Try.scala:255)
[error] 	at scala.util.Success.map(Try.scala:213)
[error] 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[error] 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[error] 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:750)
[error] (update) lmcoursier.internal.shaded.coursier.error.FetchError$DownloadingArtifacts: Error fetching artifacts:
[error] https://repo1.maven.org/maven2/io/get-coursier/interface/0.0.17/interface-0.0.17.jar: download error: Caught java.nio.file.AccessDeniedException (C:\Users\TsinghuaIC\AppData\Local\Coursier\Cache\v1\https\repo1.maven.org\maven2\io\get-coursier\interface\0.0.17\.interface-0.0.17.jar.part -> C:\Users\TsinghuaIC\AppData\Local\Coursier\Cache\v1\https\repo1.maven.org\maven2\io\get-coursier\interface\0.0.17\interface-0.0.17.jar) while downloading https://repo1.maven.org/maven2/io/get-coursier/interface/0.0.17/interface-0.0.17.jar
